version: "3"
services:

  grin-node:
    image: vanities/grin:latest
    working_dir: /grin/target/release/
    network_mode: "host"
    command: ./grin --floonet

  grin-wallet:
    image: vanities/grin:latest
    working_dir: /grin/target/release/
    network_mode: "host"
    command: bash -c "echo 'password' | ./grin --floonet wallet listen"

  grin-miner:
    image: vanities/grin:latest
    volumes:
      - "./grin-miner.toml:/grin-miner/target/debug/grin-miner.toml"
    ports:
      - "3416:3416" # stratum
    volumes:
      - /dev/hugepages:/dev/hugepages
    devices:
      # AMD GPU DEVICE passed in so that we can mine
      - /dev/dri:/dev/dri
      - /dev/mem:/dev/mem
    network_mode: "host"
    working_dir: /grin-miner/target/debug/
    command: ./grin-miner --floonet

    
    #ports:
    #  - "3413:3413" # api
    #  - "3414:3414"
    #  - "3415:3415" # wallet
